# Generated by Django 4.2.20 on 2025-05-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0002_alter_externeverwijzingconfig_options_and_more"),
        ("producten", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="documenten_api",
            field=models.ForeignKey(
                default=None,
                help_text="de api waar dit document zich bevind.",
                limit_choices_to={"type": "verzoektypen"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documenten",
                to="producttypen.externeverwijzingconfig",
                verbose_name="documenten api",
            ),
            preserve_default=False,
        ),
    ]
