# Generated by Django 4.2.20 on 2025-05-08 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eigenaar",
            old_name="klantnummer",
            new_name="partijnummer",
        ),
        migrations.AlterField(
            model_name="eigenaar",
            name="partijnummer",
            field=models.CharField(
                blank=True,
                help_text="generiek veld voor de identificatie van een Partij (gedefinieerd in de Klantinteracties API).",
                max_length=10,
                validators=[django.core.validators.validate_integer],
                verbose_name="Partijnummer",
            ),
        ),
    ]
