# Generated by Django 4.2.20 on 2025-04-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eigenaar",
            unique_together={
                ("bsn", "product"),
                ("vestigingsnummer", "product"),
                ("kvk_nummer", "product"),
                ("klantnummer", "product"),
            },
        ),
    ]
