# Generated by Django 4.2.20 on 2025-04-28 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eigenaar",
            name="klantnummer",
        ),
        migrations.AddField(
            model_name="eigenaar",
            name="partijnummer",
            field=models.CharField(
                blank=True,
                help_text="generiek veld voor de identificatie van een partij.",
                max_length=10,
                validators=[django.core.validators.validate_integer],
                verbose_name="partijnummer",
            ),
        ),
    ]
