# Generated by Django 4.2.20 on 2025-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eigenaar",
            name="klantnummer",
            field=models.CharField(
                blank=True,
                help_text="generiek veld voor de identificatie van een klant of partij.",
                max_length=50,
                verbose_name="Klantnummer",
            ),
        ),
    ]
