# Generated by Django 5.2.1 on 2025-06-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0003_alter_eigenaar_klantnummer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taak",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        help_text="Uuid van de taak.", verbose_name="uuid"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Het product waarbij deze taak hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taken",
                        to="producten.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taak",
                "verbose_name_plural": "Taken",
                "unique_together": {("product", "uuid")},
            },
        ),
        migrations.CreateModel(
            name="Zaak",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        help_text="Uuid van de zaak.", verbose_name="uuid"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Het product waarbij deze zaak hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zaken",
                        to="producten.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaak",
                "verbose_name_plural": "Zaken",
                "unique_together": {("product", "uuid")},
            },
        ),
    ]
