# Generated by Django 5.2.3 on 2025-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0005_alter_product_prijs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('initieel', 'Initieel'), ('gereed', 'Gereed'), ('actief', 'Actief'), ('ingetrokken', 'Ingetrokken'), ('geweigerd', 'Geweigerd'), ('verlopen', 'Verlopen')], default='initieel', help_text="De status opties worden bepaald door het veld 'toegestane statussen' van het gerelateerde producttype. Via start & eind_datum kan de status automatisch naar ACTIEF of VERLOPEN worden gezet (mits deze statussen zijn toegestaan op het producttype).", verbose_name='status'),
        ),
    ]
