# Generated by Django 5.2.3 on 2025-08-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0007_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gepubliceerd',
            field=models.BooleanField(default=False, help_text='Geeft aan of het product getoond kan worden.', verbose_name='gepubliceerd'),
        ),
    ]
