# Generated by Django 5.2.3 on 2025-08-19 16:11

import openproduct.urn.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0008_alter_product_gepubliceerd'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aanvraag_zaak_url',
            field=models.URLField(blank=True, help_text='De zaak waaruit dit product is ontstaan.', null=True, verbose_name='aanvraag zaak url'),
        ),
        migrations.AddField(
            model_name='product',
            name='aanvraag_zaak_urn',
            field=openproduct.urn.fields.UrnField(blank=True, help_text='De zaak waaruit dit product is ontstaan.', null=True, verbose_name='aanvraag zaak urn'),
        ),
    ]
