# Generated by Django 5.2.3 on 2025-08-22 12:12

import openproduct.urn.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0009_product_aanvraag_zaak_url_product_aanvraag_zaak_urn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aanvraag_zaak_url',
            field=openproduct.urn.fields.UrlField(blank=True, help_text='De zaak waaruit dit product is ontstaan.', null=True, verbose_name='aanvraag zaak url'),
        ),
    ]
