# Generated by Django 4.2.17 on 2025-04-04 11:44

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0014_alter_contentelementtranslation_options_and_more"),
        ("producten", "0009_alter_product_dataobject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_type",
        ),
        migrations.AddField(
            model_name="product",
            name="producttype",
            field=models.ForeignKey(
                help_text="Het type van dit product",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producten",
                to="producttypen.producttype",
                verbose_name="Producttype",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="dataobject",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Dataobject van dit product. Wordt gevalideerd met het `dataobject_schema` uit het producttype.",
                null=True,
                verbose_name="dataobject",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="eind_datum",
            field=models.DateField(
                blank=True,
                help_text="De einddatum van dit product. Op deze datum zal de status van het product automatisch naar VERLOPEN worden gezet. Op het moment dat de eind_datum wordt ingevuld moet de status VERLOPEN op het producttype zijn toegestaan.",
                null=True,
                verbose_name="eind datum",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="start_datum",
            field=models.DateField(
                blank=True,
                help_text="De start datum van dit product. Op deze datum zal de status van het product automatisch naar ACTIEF worden gezet. Op het moment dat de start_datum wordt ingevuld moet de status ACTIEF op het producttype zijn toegestaan.",
                null=True,
                verbose_name="start datum",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("initieel", "Initieel"),
                    ("gereed", "Gereed"),
                    ("actief", "Actief"),
                    ("ingetrokken", "Ingetrokken"),
                    ("geweigerd", "Geweigerd"),
                    ("verlopen", "Verlopen"),
                ],
                default="initieel",
                help_text="De status opties worden bepaald door het veld 'toegestane statussen' van het gerelateerde producttype.",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="verbruiksobject",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Verbruiksobject van dit product. Wordt gevalideerd met het `verbruiksobject_schema` uit het producttype.",
                null=True,
                verbose_name="verbruiksobject",
            ),
        ),
    ]
