# Generated by Django 5.2.3 on 2025-10-03 13:52

import openproduct.urn.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0009_alter_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Product', 'verbose_name_plural': 'Producten'},
        ),
        migrations.AddField(
            model_name='product',
            name='aanvraag_zaak_url',
            field=openproduct.urn.fields.UrlField(blank=True, help_text='De zaak waaruit dit product is ontstaan.', null=True, verbose_name='aanvraag zaak url'),
        ),
        migrations.AddField(
            model_name='product',
            name='aanvraag_zaak_urn',
            field=openproduct.urn.fields.UrnField(blank=True, help_text='De zaak waaruit dit product is ontstaan.', null=True, verbose_name='aanvraag zaak urn'),
        ),
    ]
