# Generated by Django 5.2.7 on 2025-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0010_alter_product_options_product_aanvraag_zaak_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('initieel', 'Initieel'), ('in_aanvraag', 'In aanvraag'), ('gereed', 'Gereed'), ('actief', 'Actief'), ('ingetrokken', 'Ingetrokken'), ('geweigerd', 'Geweigerd'), ('verlopen', 'Verlopen')], default='initieel', help_text="De status opties worden bepaald door het veld 'toegestane statussen' van het gerelateerde producttype. Via start & eind_datum kan de status automatisch naar ACTIEF of VERLOPEN worden gezet (mits deze statussen zijn toegestaan op het producttype).", max_length=100, verbose_name='status'),
        ),
    ]
