# Generated by Django 4.2.17 on 2025-04-04 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0010_remove_product_product_type_product_producttype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Uuid van het document.",
                        null=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Het product waarbij dit document hoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documenten",
                        to="producten.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documenten",
                "unique_together": {("product", "uuid")},
            },
        ),
    ]
