# Generated by Django 5.2.3 on 2025-08-26 11:47

import django.contrib.postgres.fields
import openproduct.urn.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0010_alter_product_aanvraag_zaak_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gerelateerde_zaken_url',
            field=django.contrib.postgres.fields.ArrayField(base_field=openproduct.urn.fields.UrlField(), blank=True, default=list, help_text='Een gerelateerde zaak.', size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='gerelateerde_zaken_urn',
            field=django.contrib.postgres.fields.ArrayField(base_field=openproduct.urn.fields.UrnField(), blank=True, default=list, help_text='Een gerelateerde zaak.', size=None),
        ),
    ]
