# Generated by Django 5.2.7 on 2025-11-14 11:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frequentie',
            field=models.CharField(blank=True, choices=[('eenmalig', 'Eenmalig'), ('maandelijks', 'Maandelijks'), ('jaarlijks', 'Jaarlijks')], help_text='De frequentie van betalingen.', max_length=30, verbose_name='Prijs frequentie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prijs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='De prijs van het product.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='prijs'),
        ),
    ]
