# Generated by Django 4.2.17 on 2025-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0011_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                help_text="Uuid van het document.", verbose_name="uuid"
            ),
        ),
    ]
