# Generated by Django 5.2.7 on 2025-11-12 15:47
from django.conf import settings
from django.db import migrations
from django.db.migrations.exceptions import IrreversibleError


def migrate_externe_verwijzingen(apps, schema_editor):
    UrnMappingConfig = apps.get_model('urn', 'UrnMappingConfig')
    ExterneVerwijzingConfig = apps.get_model('producttypen', 'ExterneVerwijzingConfig')

    def _update(model, url):

        mapping = UrnMappingConfig.objects.filter(url=url).first()

        if not mapping and model.objects.count() > 0 and settings.REQUIRE_URL_URN_MAPPING:
            raise IrreversibleError("url '{}' heeft geen urn mapping".format(url))

        for obj in model.objects.iterator():
            obj.url = f"{url}/{obj.uuid}"
            if mapping:
                obj.urn = f"{mapping.urn}:{obj.uuid}"
            obj.save()

    externe_verwijzing_config = ExterneVerwijzingConfig.objects.first()

    if externe_verwijzing_config is None:
        return

    Zaak = apps.get_model('producten', 'Zaak')
    _update(Zaak, externe_verwijzing_config.zaken_url)

    Taak = apps.get_model('producten', 'Taak')
    _update(Taak, externe_verwijzing_config.taken_url)

    Document = apps.get_model('producten', 'Document')
    _update(Document, externe_verwijzing_config.documenten_url)

class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0012_alter_document_unique_together_and_more'),
        ('producttypen', '0005_externeverwijzingconfig_taken_url_and_more'),
        ('urn', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_externe_verwijzingen),
        migrations.RemoveField(
            model_name='document',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='taak',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='zaak',
            name='uuid',
        ),
    ]
