# Generated by Django 5.2.7 on 2025-11-12 15:44

import openproduct.urn.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0012_alter_product_frequentie_alter_product_prijs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taak',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='zaak',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='urn',
            field=openproduct.urn.fields.UrnField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taak',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taak',
            name='urn',
            field=openproduct.urn.fields.UrnField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zaak',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zaak',
            name='urn',
            field=openproduct.urn.fields.UrnField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taak',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zaak',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('product', 'url'), ('product', 'urn')},
        ),
        migrations.AlterUniqueTogether(
            name='taak',
            unique_together={('product', 'url'), ('product', 'urn')},
        ),
        migrations.AlterUniqueTogether(
            name='zaak',
            unique_together={('product', 'url'), ('product', 'urn')},
        ),
    ]
