# Generated by Django 5.2.7 on 2025-11-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0014_remove_document_uuid_remove_taak_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-id',), 'verbose_name': 'Document', 'verbose_name_plural': 'Documenten'},
        ),
        migrations.AlterModelOptions(
            name='taak',
            options={'ordering': ('-id',), 'verbose_name': 'Taak', 'verbose_name_plural': 'Taken'},
        ),
        migrations.AlterModelOptions(
            name='zaak',
            options={'ordering': ('-id',), 'verbose_name': 'Zaak', 'verbose_name_plural': 'Zaken'},
        ),
    ]
