# Generated by Django 5.2.8 on 2026-04-28 12:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0015_alter_document_options_alter_taak_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dataobject',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Dataobject van dit product. Wordt gevalideerd met het `dataobject_schema` uit het producttype. De inhoud kan worden gepubliceerd op overheidsportalen en mag GEEN interne informatie bevatten die niet bestemd is voor de eigenaar.', null=True, verbose_name='dataobject'),
        ),
    ]
