# Generated by Django 5.2.13 on 2026-06-18 14:47

import openproduct.urn.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0016_alter_product_dataobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aanvraag_zaak_urn',
            field=openproduct.urn.fields.UrnField(blank=True, help_text='De zaak waaruit dit product is ontstaan. (`<organisatie>:<systeem>:<component>:<resource>:<identificatie>`)', null=True, verbose_name='aanvraag zaak urn'),
        ),
    ]
