# Generated by Django 5.2.17 on 2026-10-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0017_alter_product_aanvraag_zaak_urn'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtype',
            field=models.CharField(blank=True, help_text='het subtype is alleen toegestaan (en verplicht) wanneer producttypen subtypen heeft gedefinieerd. Het product subtypen moet een van de producttypen subtypen zijn', max_length=255, verbose_name='subtype'),
        ),
    ]
