# Generated by Django 5.2.3 on 2025-10-07 15:12

import openproduct.urn.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrnMappingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn', openproduct.urn.fields.BaseUrnField(help_text='Basis urn (<organisatie>:<systeem>:<component>:<resource>)', unique=True, verbose_name='Urn')),
                ('url', models.URLField(help_text='Basis url van een urn.', unique=True, verbose_name='basis url')),
            ],
            options={
                'verbose_name': 'Urn Mapping',
                'verbose_name_plural': 'Urn Mappings',
            },
        ),
    ]
