# Generated by Django 5.2.12 on 2026-04-09 09:37

import openproduct.urn.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urnmappingconfig',
            name='urn',
            field=openproduct.urn.fields.BaseUrnField(help_text='Basis urn (RFC 8141) (voorbeeld: urn:nld:<organisatie>:<systeem>:<component>:<resource>)', unique=True, verbose_name='Urn'),
        ),
    ]
