# Generated by Django 5.2.1 on 2025-06-11 08:04

from django.db import migrations, models

def move_names(apps, schema_editor):
    Contact = apps.get_model('locaties', 'Contact')
    for contact in Contact.objects.iterator():
        contact.naam = f"{contact.voornaam} {contact.achternaam}"
        contact.save()

class Migration(migrations.Migration):

    dependencies = [
        ("locaties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="naam",
            field=models.CharField(
                help_text="Naam van het contact (persoon, afdeling, enz..)",
                max_length=255,
                verbose_name="naam",
            ),
        ),
        migrations.RunPython(move_names),
        migrations.RemoveField(
            model_name="contact",
            name="achternaam",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="voornaam",
        ),
    ]
