# Generated by Django 5.2.3 on 2025-09-19 08:33

import openproduct.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locaties', '0002_remove_contact_achternaam_remove_contact_voornaam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatie',
            name='postcode',
            field=models.CharField(blank=True, max_length=7, validators=[openproduct.utils.validators.CustomRegexValidator(message='Invalid postal code. A postal code must consist of 4 numbers followed by two capital letters (e.g. 1234 AB).', regex='^[1-9][0-9]{3}\\s?[A-Za-z]{2}$')], verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='postcode',
            field=models.CharField(blank=True, max_length=7, validators=[openproduct.utils.validators.CustomRegexValidator(message='Invalid postal code. A postal code must consist of 4 numbers followed by two capital letters (e.g. 1234 AB).', regex='^[1-9][0-9]{3}\\s?[A-Za-z]{2}$')], verbose_name='postcode'),
        ),
    ]
