# Generated by Django 4.2.17 on 2025-03-25 16:40

from django.db import migrations, models
import openproduct.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("locaties", "0005_alter_locatie_postcode_alter_organisatie_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locatie",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email adres"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="locatie",
            name="huisnummer",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="huisnummer"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="locatie",
            name="postcode",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    openproduct.utils.validators.CustomRegexValidator(
                        message="Invalid postal code. A postal code must consist of 4 numbers followed by a space and two capital letters (e.g. 1234 AB).",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="locatie",
            name="stad",
            field=models.CharField(blank=True, max_length=255, verbose_name="stad"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="locatie",
            name="straat",
            field=models.CharField(blank=True, max_length=255, verbose_name="straat"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="locatie",
            name="telefoonnummer",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[openproduct.utils.validators.validate_phone_number],
                verbose_name="telefoonnummer",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email adres"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="huisnummer",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="huisnummer"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="postcode",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    openproduct.utils.validators.CustomRegexValidator(
                        message="Invalid postal code. A postal code must consist of 4 numbers followed by a space and two capital letters (e.g. 1234 AB).",
                        regex="^[1-9][0-9]{3} [A-Z]{2}$",
                    )
                ],
                verbose_name="postcode",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="stad",
            field=models.CharField(blank=True, max_length=255, verbose_name="stad"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="straat",
            field=models.CharField(blank=True, max_length=255, verbose_name="straat"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organisatie",
            name="telefoonnummer",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[openproduct.utils.validators.validate_phone_number],
                verbose_name="telefoonnummer",
            ),
            preserve_default=False,
        ),
    ]
