# Generated by Django 4.2.20 on 2025-05-19 14:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actie",
            name="mapping",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="De mapping tussen de velden in Open Product & DMN variabele",
                null=True,
                verbose_name="mapping",
            ),
        ),
        migrations.AddField(
            model_name="prijsregel",
            name="mapping",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="De mapping tussen de velden in Open Product & DMN variabele",
                null=True,
                verbose_name="mapping",
            ),
        ),
    ]
