# Generated by Django 4.2.20 on 2025-05-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thema",
            name="hoofd_thema",
            field=models.ForeignKey(
                blank=True,
                help_text="Het hoofd thema waaronder dit thema valt.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_themas",
                to="producttypen.thema",
                verbose_name="hoofd thema",
            ),
        ),
    ]
