# Generated by Django 4.2.20 on 2025-05-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externeverwijzingconfig",
            options={
                "verbose_name": "Externe verwijzingen configuratie",
                "verbose_name_plural": "Externe verwijzingen configuraties",
            },
        ),
        migrations.RemoveField(
            model_name="externeverwijzingconfig",
            name="documenten_url",
        ),
        migrations.RemoveField(
            model_name="externeverwijzingconfig",
            name="processen_url",
        ),
        migrations.RemoveField(
            model_name="externeverwijzingconfig",
            name="verzoektypen_url",
        ),
        migrations.RemoveField(
            model_name="externeverwijzingconfig",
            name="zaaktypen_url",
        ),
        migrations.AddField(
            model_name="externeverwijzingconfig",
            name="basis_url",
            field=models.URLField(
                blank=True,
                help_text="Basis url van van de externe verwijzing.",
                unique=True,
                verbose_name="basis url",
            ),
        ),
        migrations.AddField(
            model_name="externeverwijzingconfig",
            name="naam",
            field=models.CharField(
                default=None,
                help_text="naam van de externe verwijzing.",
                max_length=255,
                unique=True,
                verbose_name="naam",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="externeverwijzingconfig",
            name="type",
            field=models.CharField(
                choices=[
                    ("DMN", "DMN"),
                    ("documenten", "Documenten"),
                    ("zaaktypen", "Zaaktypen"),
                    ("processen", "Processen"),
                    ("verzoektypen", "Verzoektypen"),
                ],
                default=None,
                help_text="type van de externe verwijzing.",
                verbose_name="type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proces",
            name="processen_api",
            field=models.ForeignKey(
                default=None,
                help_text="de api waar dit proces zich bevind.",
                limit_choices_to={"type": "processen"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processen",
                to="producttypen.externeverwijzingconfig",
                verbose_name="processen api",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verzoektype",
            name="verzoektypen_api",
            field=models.ForeignKey(
                default=None,
                help_text="de api waar dit verzoekttype zich bevind.",
                limit_choices_to={"type": "verzoektypen"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verzoekttypen",
                to="producttypen.externeverwijzingconfig",
                verbose_name="verzoekttypen api",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="zaaktypen_api",
            field=models.ForeignKey(
                default=None,
                help_text="de api waar dit zaaktype zich bevind.",
                limit_choices_to={"type": "zaaktypen"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zaaktypen",
                to="producttypen.externeverwijzingconfig",
                verbose_name="zaaktypen api",
            ),
            preserve_default=False,
        ),
    ]
