# Generated by Django 5.2.1 on 2025-06-02 13:36

import django.core.serializers.json
import openproduct.producttypen.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0002_alter_producttype_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="actie",
            name="mapping",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="De mapping tussen de velden in Open Product & DMN variabele.",
                null=True,
                validators=[
                    openproduct.producttypen.models.validators.validate_dmn_mapping
                ],
                verbose_name="mapping",
            ),
        ),
        migrations.AddField(
            model_name="prijsregel",
            name="mapping",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="De mapping tussen de velden in Open Product & DMN variabele",
                null=True,
                validators=[
                    openproduct.producttypen.models.validators.validate_dmn_mapping
                ],
                verbose_name="mapping",
            ),
        ),
    ]
