# Generated by Django 5.2.1 on 2025-06-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0002_alter_producttype_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thema",
            name="hoofd_thema",
            field=models.ForeignKey(
                blank=True,
                help_text="Het hoofd thema waaronder dit thema valt.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_themas",
                to="producttypen.thema",
                verbose_name="hoofd thema",
            ),
        ),
    ]
