# Generated by Django 5.2.3 on 2025-06-27 07:13

import openproduct.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0005_externeverwijzingconfig_taken_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='toegestane_statussen',
            field=openproduct.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('in aanvraag', 'In aanvraag'), ('gereed', 'Gereed'), ('actief', 'Actief'), ('ingetrokken', 'Ingetrokken'), ('geweigerd', 'Geweigerd'), ('verlopen', 'Verlopen')]), blank=True, default=list, help_text='toegestane statussen voor producten van dit type.', size=None, verbose_name='toegestane statussen'),
        ),
    ]
