# Generated by Django 5.2.3 on 2025-08-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0006_alter_producttype_toegestane_statussen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='gepubliceerd',
        ),
        migrations.AddField(
            model_name='producttype',
            name='publicatie_eind_datum',
            field=models.DateField(blank=True, help_text='De datum waarop het producttype gepubliceerd is', null=True, verbose_name='publicatie startdatum'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='publicatie_start_datum',
            field=models.DateField(blank=True, help_text='De datum waarop het producttype gepubliceerd is', null=True, verbose_name='publicatie startdatum'),
        ),
        migrations.AlterField(
            model_name='thema',
            name='gepubliceerd',
            field=models.BooleanField(default=False, help_text='Geeft aan of het thema getoond kan worden.', verbose_name='gepubliceerd'),
        ),
    ]
