# Generated by Django 5.2.3 on 2025-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0007_remove_producttype_gepubliceerd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentelementtranslation',
            name='naam',
            field=models.CharField(default=1, help_text='De naam van dit content element', max_length=50, verbose_name='naam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentlabel',
            name='type',
            field=models.CharField(choices=[('intern', 'Intern'), ('extern', 'Extern'), ('aanvullend', 'Aanvullende informatie')], default='extern', help_text='Gebruik om onderscheid te maken tussen interne, externe of aanvullende labels', max_length=20),
        ),
    ]
