# Generated by Django 5.2.7 on 2025-10-24 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0008_alter_producttype_toegestane_statussen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='doelgroep',
            field=models.CharField(choices=[('burgers', 'Burgers'), ('interne_organisatie', 'Interne organisatie'), ('samenwerkingspartners', 'Samenwerkingspartners'), ('bedrijven_en_instellingen', 'Bedrijven en instellingen')], default='burgers', help_text='De doelgroep van het producttype.', verbose_name='doelgroep'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='uniforme_product_naam',
            field=models.ForeignKey(blank=True, help_text='Uniforme product naam gedefinieerd door de overheid.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producttypen', to='producttypen.uniformeproductnaam', verbose_name='Uniforme Product naam'),
        ),
    ]
