# Generated by Django 5.2.7 on 2025-10-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0008_alter_producttype_toegestane_statussen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentelementtranslation',
            name='aanvullende_info',
            field=models.TextField(default='', help_text='De aanvullende info van dit content element', verbose_name='aanvullende info'),
        ),
    ]
