# Generated by Django 5.2.7 on 2025-11-04 12:51

import openproduct.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0009_producttype_doelgroep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='doelgroep',
            field=models.CharField(choices=[('burgers', 'Burgers'), ('interne_organisatie', 'Interne organisatie'), ('samenwerkingspartners', 'Samenwerkingspartners'), ('bedrijven_en_instellingen', 'Bedrijven en instellingen')], help_text='De doelgroep van het producttype.', max_length=100, verbose_name='doelgroep'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='toegestane_statussen',
            field=openproduct.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('in_aanvraag', 'In aanvraag'), ('gereed', 'Gereed'), ('actief', 'Actief'), ('ingetrokken', 'Ingetrokken'), ('geweigerd', 'Geweigerd'), ('verlopen', 'Verlopen')], max_length=100), blank=True, default=list, help_text='toegestane statussen voor producten van dit type.', size=None, verbose_name='toegestane statussen'),
        ),
    ]
