# Generated by Django 5.2.7 on 2025-11-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0010_alter_producttype_doelgroep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('-id',), 'permissions': (('producten', 'alter products of this producttype'),), 'verbose_name': 'Producttype', 'verbose_name_plural': 'Producttypen'},
        ),
    ]
