# Generated by Django 5.2.7 on 2025-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0010_alter_producttype_doelgroep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentelementtranslation',
            name='aanvullende_informatie',
            field=models.TextField(blank=True, help_text='De aanvullende informatie van dit content element', verbose_name='aanvullende informatie'),
        ),
    ]
