# Generated by Django 5.2.7 on 2025-11-13 09:55
from django.conf import settings
from django.db import migrations
from django.db.migrations.exceptions import IrreversibleError



def migrate_externe_verwijzingen(apps, schema_editor):
    UrnMappingConfig = apps.get_model('producttypen', 'URNMappingConfig')
    ExterneVerwijzingConfig = apps.get_model('producttypen', 'ExterneVerwijzingConfig')

    def _update(model, url):

        mapping = UrnMappingConfig.objects.filter(url=url).first()

        if not mapping and model.objects.count() > 0 and settings.REQUIRE_URL_URN_MAPPING:
            raise IrreversibleError("url '{}' heeft geen urn mapping".format(url))

        for obj in model.objects.iterator():
            obj.url = f"{url}/{obj.uuid}"
            if mapping:
                obj.urn = f"{mapping.urn}:{obj.uuid}"
            obj.save()

    externe_verwijzing_config = ExterneVerwijzingConfig.get_solo()

    ZaakType = apps.get_model('producttypen', 'ZaakType')
    _update(ZaakType, externe_verwijzing_config.zaaktypen_url)

    VerzoekType = apps.get_model('producttypen', 'VerzoekType')
    _update(VerzoekType, externe_verwijzing_config.verzoektypen_url)

    Proces = apps.get_model('producttypen', 'Proces')
    _update(Proces, externe_verwijzing_config.processen_url)

class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0011_alter_proces_unique_together_and_more'),
        ('producttypen', '0005_externeverwijzingconfig_taken_url_and_more'),
        ('urn', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_externe_verwijzingen),
        migrations.RemoveField(
            model_name='proces',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='verzoektype',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='zaaktype',
            name='uuid',
        ),
    ]
