# Generated by Django 5.2.7 on 2025-11-21 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0011_contentelementtranslation_aanvullende_informatie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('read_only', 'Read-only'), ('read_and_write', 'Read and write')], help_text='Permission mode', max_length=20, verbose_name='mode')),
                ('producttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttype_permissions', to='producttypen.producttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttype_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductType Permission',
                'unique_together': {('user', 'producttype')},
            },
        ),
    ]
