# Generated by Django 5.2.7 on 2025-11-13 09:50

import openproduct.urn.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0011_contentelementtranslation_aanvullende_informatie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proces',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='verzoektype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='zaaktype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='proces',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proces',
            name='urn',
            field=openproduct.urn.fields.UrnField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verzoektype',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verzoektype',
            name='urn',
            field=openproduct.urn.fields.UrnField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zaaktype',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zaaktype',
            name='urn',
            field=openproduct.urn.fields.UrnField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proces',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='verzoektype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zaaktype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='proces',
            unique_together={('producttype', 'url'), ('producttype', 'urn')},
        ),
        migrations.AlterUniqueTogether(
            name='verzoektype',
            unique_together={('producttype', 'url'), ('producttype', 'urn')},
        ),
        migrations.AlterUniqueTogether(
            name='zaaktype',
            unique_together={('producttype', 'url'), ('producttype', 'urn')},
        ),
    ]
