# Generated by Django 5.2.7 on 2025-11-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0013_remove_proces_uuid_remove_verzoektype_uuid_and_more'),
        ('producten', '0014_remove_document_uuid_remove_taak_uuid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExterneVerwijzingConfig',
        ),
    ]
