# Generated by Django 4.2.17 on 2025-04-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locaties", "0006_alter_locatie_email_alter_locatie_huisnummer_and_more"),
        ("producttypen", "0014_alter_contentelementtranslation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bestand",
            options={
                "verbose_name": "Producttype bestand",
                "verbose_name_plural": "Producttype bestanden",
            },
        ),
        migrations.AlterModelOptions(
            name="contentelement",
            options={
                "ordering": ("producttype", "order"),
                "verbose_name": "content element",
                "verbose_name_plural": "content elementen",
            },
        ),
        migrations.AlterModelOptions(
            name="link",
            options={
                "verbose_name": "Producttype link",
                "verbose_name_plural": "Producttype links",
            },
        ),
        migrations.AlterModelOptions(
            name="producttype",
            options={
                "verbose_name": "Producttype",
                "verbose_name_plural": "Producttypen",
            },
        ),
        migrations.RenameField(
            model_name="actie",
            old_name="product_type",
            new_name="producttype",
        ),
        migrations.RenameField(
            model_name="externecode",
            old_name="product_type",
            new_name="producttype",
        ),
        migrations.RenameField(
            model_name="parameter",
            old_name="product_type",
            new_name="producttype",
        ),
        migrations.AlterUniqueTogether(
            name="prijs",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="proces",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="verzoektype",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="zaaktype",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="bestand",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="contentelement",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="link",
            name="product_type",
        ),
        migrations.AddField(
            model_name="bestand",
            name="producttype",
            field=models.ForeignKey(
                help_text="Het producttype waarbij dit bestand hoort.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bestanden",
                to="producttypen.producttype",
                verbose_name="producttype",
            ),
        ),
        migrations.AddField(
            model_name="contentelement",
            name="producttype",
            field=models.ForeignKey(
                help_text="Het producttype van dit content element",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_elementen",
                to="producttypen.producttype",
                verbose_name="label",
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="producttype",
            field=models.ForeignKey(
                help_text="Het producttype waarbij deze link hoort.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="producttypen.producttype",
                verbose_name="Producttype",
            ),
        ),
        migrations.AddField(
            model_name="prijs",
            name="producttype",
            field=models.ForeignKey(
                help_text="Het producttype waarbij deze prijs hoort.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prijzen",
                to="producttypen.producttype",
                verbose_name="producttype",
            ),
        ),
        migrations.AddField(
            model_name="proces",
            name="producttype",
            field=models.ForeignKey(
                help_text="Het producttype waarbij dit proces hoort.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processen",
                to="producttypen.producttype",
                verbose_name="producttype",
            ),
        ),
        migrations.AddField(
            model_name="verzoektype",
            name="producttype",
            field=models.ForeignKey(
                help_text="Het producttype waarbij dit verzoektype hoort.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verzoektypen",
                to="producttypen.producttype",
                verbose_name="producttype",
            ),
        ),
        migrations.AddField(
            model_name="zaaktype",
            name="producttype",
            field=models.ForeignKey(
                help_text="Het producttype waarbij dit zaaktype hoort.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zaaktypen",
                to="producttypen.producttype",
                verbose_name="producttype",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="code",
            field=models.CharField(
                help_text="code van het producttype.",
                max_length=255,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="contacten",
            field=models.ManyToManyField(
                blank=True,
                help_text="De contacten verantwoordelijk voor het producttype.",
                related_name="producttypen",
                to="locaties.contact",
                verbose_name="contacten",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="dataobject_schema",
            field=models.ForeignKey(
                blank=True,
                help_text="JSON schema om het dataobject van een gerelateerd product te valideren.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producttypen_dataobject_schemas",
                to="producttypen.jsonschema",
                verbose_name="dataobject schema",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="interne_opmerkingen",
            field=models.TextField(
                blank=True,
                help_text="Interne opmerkingen over het producttype.",
                verbose_name="interne opmerkingen",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="locaties",
            field=models.ManyToManyField(
                blank=True,
                help_text="De locaties waar het product beschikbaar is.",
                related_name="producttypen",
                to="locaties.locatie",
                verbose_name="locaties",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="organisaties",
            field=models.ManyToManyField(
                blank=True,
                help_text="organisaties die dit het product aanbieden.",
                related_name="producttypen",
                to="locaties.organisatie",
                verbose_name="organisaties",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="themas",
            field=models.ManyToManyField(
                blank=True,
                help_text="thema's waaraan het producttype is gelinkt.",
                related_name="producttypen",
                to="producttypen.thema",
                verbose_name="thema's",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="uniforme_product_naam",
            field=models.ForeignKey(
                help_text="Uniforme product naam gedefinieerd door de overheid.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="producttypen",
                to="producttypen.uniformeproductnaam",
                verbose_name="Uniforme Product naam",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="verbruiksobject_schema",
            field=models.ForeignKey(
                blank=True,
                help_text="JSON schema om het verbruiksobject van een gerelateerd product te valideren.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producttypen_verbruiksobject_schemas",
                to="producttypen.jsonschema",
                verbose_name="verbruiksobject schema",
            ),
        ),
        migrations.AlterField(
            model_name="producttypetranslation",
            name="naam",
            field=models.CharField(
                help_text="naam van het producttype.",
                max_length=255,
                verbose_name="producttype naam",
            ),
        ),
        migrations.AlterField(
            model_name="producttypetranslation",
            name="samenvatting",
            field=models.TextField(
                default="",
                help_text="Korte samenvatting van het producttype.",
                verbose_name="samenvatting",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="externecode",
            unique_together={("producttype", "naam")},
        ),
        migrations.AlterUniqueTogether(
            name="parameter",
            unique_together={("producttype", "naam")},
        ),
        migrations.AlterUniqueTogether(
            name="prijs",
            unique_together={("producttype", "actief_vanaf")},
        ),
        migrations.AlterUniqueTogether(
            name="proces",
            unique_together={("producttype", "uuid")},
        ),
        migrations.AlterUniqueTogether(
            name="verzoektype",
            unique_together={("producttype", "uuid")},
        ),
        migrations.AlterUniqueTogether(
            name="zaaktype",
            unique_together={("producttype", "uuid")},
        ),
        migrations.RemoveField(
            model_name="prijs",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="proces",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="verzoektype",
            name="product_type",
        ),
        migrations.RemoveField(
            model_name="zaaktype",
            name="product_type",
        ),
    ]
