# Generated by Django 4.2.17 on 2025-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "producttypen",
            "0015_alter_bestand_options_alter_contentelement_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="externeverwijzingconfig",
            name="documenten_url",
            field=models.URLField(
                blank=True,
                help_text="Basis url van documenten.",
                verbose_name="documenten url",
            ),
        ),
    ]
