# Generated by Django 5.2.8 on 2026-01-07 09:03

import openproduct.urn.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0015_producttypepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='eigenaar',
            field=openproduct.urn.fields.UrnField(blank=True, help_text='Basis urn (<organisatie>:<systeem>:<component>:<resource>)', null=True, verbose_name='eigenaar'),
        ),
    ]
