# Generated by Django 5.2.8 on 2025-12-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0015_producttypepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="thema",
            name="content_elementen",
            field=models.ManyToManyField(
                blank=True,
                help_text="Content elementen gekoppeld aan dit thema of subthema",
                related_name="themas",
                to="producttypen.contentelement",
                verbose_name="Content Elementen",
            ),
        ),
    ]
