# Generated by Django 5.2.8 on 2026-01-08 09:23

import openproduct.urn.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0015_producttypepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='eigenaar',
            field=openproduct.urn.fields.UrnField(blank=True, help_text='De eigenaar van dit producttype zoals een medewerker uit Open Organisatie (<organisatie>:<systeem>:<component>:<resource>:<identificatie>)', null=True, verbose_name='eigenaar'),
        ),
    ]
