# Generated by Django 5.2.8 on 2026-01-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0016_producttype_eigenaar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentelement",
            options={
                "ordering": ("producttype", "thema", "order"),
                "verbose_name": "content element",
                "verbose_name_plural": "content elementen",
            },
        ),
        migrations.AddField(
            model_name="contentelement",
            name="thema",
            field=models.ForeignKey(
                blank=True,
                help_text="Het thema of subthema van dit content element",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_elementen",
                to="producttypen.thema",
                verbose_name="thema",
            ),
        ),
        migrations.AlterField(
            model_name="contentelement",
            name="producttype",
            field=models.ForeignKey(
                blank=True,
                help_text="Het producttype van dit content element",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_elementen",
                to="producttypen.producttype",
                verbose_name="label",
            ),
        ),
    ]
