# Generated by Django 4.2.17 on 2025-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0016_externeverwijzingconfig_documenten_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externeverwijzingconfig",
            name="documenten_url",
            field=models.URLField(
                blank=True,
                help_text="Basis url van Documenten API.",
                verbose_name="Documenten API url",
            ),
        ),
        migrations.AlterField(
            model_name="externeverwijzingconfig",
            name="zaaktypen_url",
            field=models.URLField(
                blank=True,
                help_text="Basis url van Zaaktypen API.",
                verbose_name="Zaaktypen API url",
            ),
        ),
        migrations.AlterField(
            model_name="proces",
            name="uuid",
            field=models.UUIDField(
                help_text="Uuid van het proces.", verbose_name="uuid"
            ),
        ),
        migrations.AlterField(
            model_name="verzoektype",
            name="uuid",
            field=models.UUIDField(
                help_text="Uuid van het verzoektype.", verbose_name="uuid"
            ),
        ),
        migrations.AlterField(
            model_name="zaaktype",
            name="uuid",
            field=models.UUIDField(
                help_text="Uuid van het zaaktype.", verbose_name="uuid"
            ),
        ),
    ]
