# Generated by Django 5.2.8 on 2026-01-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0017_alter_contentelement_options_contentelement_thema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actie',
            name='direct_url',
            field=models.URLField(blank=True, help_text='url naar het formulier van de actie, hierbij is geen dmn nodig.', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='actie',
            name='dmn_config',
            field=models.ForeignKey(blank=True, help_text='de dmn engine waar de tabel is gedefinieerd.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acties', to='producttypen.dmnconfig', verbose_name='dmn config'),
        ),
        migrations.AlterField(
            model_name='actie',
            name='dmn_tabel_id',
            field=models.CharField(blank=True, help_text='id van de dmn tabel binnen de dmn instantie.', max_length=255, verbose_name='dmn tabel id'),
        ),
    ]
