# Generated by Django 5.2.12 on 2026-04-08 21:50

from django.db import migrations
from django.db.migrations import RunPython
from django.db.models import F, Value
from django.db.models.functions import StrIndex, Reverse, Concat, Left, Length, Right


def add_urn_prefix(apps, _):

    def _update(model, field="urn", is_full_urn=True):
        f = F(field)
        n = StrIndex(Reverse(f), Value(":"))

        model.objects.exclude(**{f"{field}__contains": "urn"}).exclude(**{f"{field}__isnull": True}).update(**{field: Concat(
            Value("urn:nld:"),
            Left(f, Length(f) - n),
            Value(":uuid:" if is_full_urn else ":"),
            Right(f, n - 1),
        )})

    UrnMappingConfig = apps.get_model("urn", "UrnMappingConfig")

    ZaakType = apps.get_model("producttypen", "ZaakType")
    VerzoekType = apps.get_model("producttypen", "VerzoekType")
    Proces = apps.get_model("producttypen", "Proces")

    Zaak = apps.get_model('producten', 'Zaak')
    Taak = apps.get_model('producten', 'Taak')
    Document = apps.get_model('producten', 'Document')
    Product = apps.get_model('producten', 'Product')

    _update(UrnMappingConfig, is_full_urn=False)
    _update(ZaakType)
    _update(VerzoekType)
    _update(Proces)
    _update(Zaak)
    _update(Taak)
    _update(Document)
    _update(Product, "aanvraag_zaak_urn")



class Migration(migrations.Migration):

    dependencies = [
        ('urn', '0001_initial'),
        ('producten', '0015_alter_document_options_alter_taak_options_and_more'),
        ('producttypen', '0018_actie_direct_url_alter_actie_dmn_config_and_more'),
    ]

    operations = [
        RunPython(add_urn_prefix, migrations.RunPython.noop),
    ]
