# Generated by Django 5.2.12 on 2026-04-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0019_prefix_urns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='publicatie_eind_datum',
            field=models.DateField(blank=True, help_text='De datum waarop de publicatie eindigt', null=True, verbose_name='publicatie einddatum'),
        ),
    ]
