# Generated by Django 5.2.13 on 2026-06-18 14:47

import openproduct.urn.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0020_alter_producttype_publicatie_eind_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='eigenaar',
            field=openproduct.urn.fields.UrnField(blank=True, help_text='De eigenaar van dit producttype zoals een medewerker uit Open Organisatie (`<organisatie>:<systeem>:<component>:<resource>:<identificatie>`)', null=True, verbose_name='eigenaar'),
        ),
    ]
