# Generated by Django 5.2.17 on 2026-09-25 09:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0021_alter_producttype_eigenaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='subtypen',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='Subtypen van het producttype', size=None, verbose_name='Subtypen'),
        ),
    ]
