# Generated by Django 5.2.17 on 2026-09-24 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producttypen", "0021_alter_producttype_eigenaar"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacetType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam van het facet",
                        max_length=255,
                        verbose_name="naam",
                    ),
                ),
                (
                    "omschrijving",
                    models.TextField(
                        blank=True,
                        help_text="Omschrijving van facet",
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "facetteerbaar",
                    models.BooleanField(
                        default=False,
                        help_text="Kun je er op filteren, flexibiliteit!",
                        verbose_name="facetteerbaar",
                    ),
                ),
                (
                    "meervoudig_toegestaan",
                    models.BooleanField(
                        default=False,
                        help_text="Kan facet meerdere keren voorkomen op producttype, bv doelgroepen",
                        verbose_name="meervoudig toegestaan",
                    ),
                ),
                (
                    "verplicht",
                    models.BooleanField(
                        default=False,
                        help_text="Verplicht voor producttype",
                        verbose_name="verplicht",
                    ),
                ),
            ],
            options={
                "verbose_name": "facettype",
                "verbose_name_plural": "facettypes",
                "ordering": ("naam",),
            },
        ),
        migrations.CreateModel(
            name="FacetWaarde",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("naam", models.CharField(max_length=255, verbose_name="naam")),
                (
                    "omschrijving",
                    models.TextField(blank=True, verbose_name="omschrijving"),
                ),
                ("actief", models.BooleanField(default=True, verbose_name="actief")),
                (
                    "facet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waarden",
                        to="producttypen.facettype",
                        verbose_name="facettype",
                    ),
                ),
            ],
            options={
                "verbose_name": "facetwaarde",
                "verbose_name_plural": "facetwaarden",
                "ordering": ("naam",),
            },
        ),
        migrations.AddField(
            model_name="producttype",
            name="facetten",
            field=models.ManyToManyField(
                blank=True,
                help_text="facetten producttypen",
                related_name="producttypen",
                to="producttypen.facetwaarde",
                verbose_name="facetten",
            ),
        ),
    ]
