# Generated by Django 5.2.17 on 2026-09-25 13:50

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0021_alter_producttype_eigenaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='actie',
            name='method',
            field=models.CharField(blank=True, choices=[('post', 'Post'), ('get', 'Get')], help_text='de method de api actie.', max_length=40, verbose_name='method'),
        ),
        migrations.AddField(
            model_name='actie',
            name='type',
            field=models.CharField(choices=[('dmn', 'DMN'), ('api', 'API'), ('formulier', 'Formulier')], default='DMN', help_text='het type waarde de actie.', max_length=40, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actie',
            name='mapping',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='De mapping van de velden die nodig is zijn de actie.', null=True, verbose_name='mapping'),
        ),
    ]
