# Generated by Django 5.2.17 on 2026-10-09 14:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0022_facettype_facetwaarde_producttype_facetten'),
    ]

    operations = [
        migrations.AddField(
            model_name='actie',
            name='method',
            field=models.CharField(blank=True, choices=[('post', 'Post'), ('get', 'Get')], help_text='De method van de api actie.', max_length=40, verbose_name='method'),
        ),
        migrations.AddField(
            model_name='actie',
            name='type',
            field=models.CharField(choices=[('dmn', 'DMN'), ('api', '**EXPERIMENTEEL** API'), ('formulier', 'Formulier')], default='', help_text='Het type van de actie.', max_length=40, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actie',
            name='mapping',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='De mapping van de velden die nodig zijn voor de actie.', null=True, verbose_name='mapping'),
        ),
    ]
