# Generated by Django 5.2.17 on 2026-10-06 10:48

from django.db import migrations


def set_type_for_existing_acties(apps, schema_editor):
    Actie = apps.get_model("producttypen", "Actie")

    acties = Actie.objects.filter(type="")
    acties.exclude(direct_url="").update(type="formulier")
    acties.filter(direct_url="").update(type="dmn")


class Migration(migrations.Migration):

    dependencies = [
        ('producttypen', '0022_actie_method_actie_type_alter_actie_mapping'),
    ]

    operations = [
        migrations.RunPython(set_type_for_existing_acties, migrations.RunPython.noop),
    ]
