openapi: 3.0.3
info:
  title: Open Producten API
  version: 0.0.0
  description: |2

    Open Producten is an API to manage product types and products.
  contact:
    email: support@maykinmedia.nl
    url: https://www.maykinmedia.nl
  license:
    name: EUPL 1.2
    url: https://opensource.org/licenses/EUPL-1.2
paths:
  /producten/:
    get:
      operationId: producten_list
      description: Deze lijst kan gefilterd wordt met query-string parameters.
      summary: Alle PRODUCTEN opvragen.
      parameters:
      - in: query
        name: gepubliceerd
        schema:
          type: boolean
      - name: page
        required: false
        in: query
        description: Een pagina binnen de gepagineerde set resultaten.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Het aantal resultaten terug te geven per pagina.
        schema:
          type: integer
      tags:
      - producten
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProductList'
          description: ''
    post:
      operationId: producten_create
      description: Maak een PRODUCT aan.
      summary: Maak een PRODUCT aan.
      tags:
      - producten
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
  /producten/{id}/:
    get:
      operationId: producten_retrieve
      description: Een specifieke PRODUCT opvragen.
      summary: Een specifiek PRODUCT opvragen.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Product.
        required: true
      tags:
      - producten
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    put:
      operationId: producten_update
      description: Werk een PRODUCT in zijn geheel bij.
      summary: Werk een PRODUCT in zijn geheel bij.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Product.
        required: true
      tags:
      - producten
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdate'
          description: ''
    patch:
      operationId: producten_partial_update
      description: Werk een PRODUCT deels bij.
      summary: Werk een PRODUCT deels bij.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Product.
        required: true
      tags:
      - producten
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProductUpdate'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductUpdate'
          description: ''
    delete:
      operationId: producten_destroy
      description: Verwijder een PRODUCT.
      summary: Verwijder een PRODUCT.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this Product.
        required: true
      tags:
      - producten
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    PaginatedProductList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    PatchedProductUpdate:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        gepubliceerd:
          type: boolean
          description: Geeft aan of het object getoond kan worden.
        aanmaak_datum:
          type: string
          format: date-time
          readOnly: true
          title: Created on
          description: De datum waarop het object is aangemaakt.
        update_datum:
          type: string
          format: date-time
          readOnly: true
          title: Updated on
          description: De datum waarop het object voor het laatst is gewijzigd.
        start_datum:
          type: string
          format: date
          description: De start datum van dit product.
        eind_datum:
          type: string
          format: date
          description: De einddatum van dit product.
        bsn:
          type: string
          nullable: true
          description: De BSN van de product eigenaar, BSN van 8 karakters moet met
            een extra 0 beginnen.
        kvk:
          type: string
          nullable: true
          title: KVK nummer
          description: Het kvk nummer van de product eigenaar
          pattern: ^[0-9]*$
          maxLength: 8
          minLength: 8
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        product_type:
          allOf:
          - $ref: '#/components/schemas/SimpleProductType'
          readOnly: true
        product_type_id:
          type: string
          format: uuid
          writeOnly: true
        gepubliceerd:
          type: boolean
          description: Geeft aan of het object getoond kan worden.
        aanmaak_datum:
          type: string
          format: date-time
          readOnly: true
          title: Created on
          description: De datum waarop het object is aangemaakt.
        update_datum:
          type: string
          format: date-time
          readOnly: true
          title: Updated on
          description: De datum waarop het object voor het laatst is gewijzigd.
        start_datum:
          type: string
          format: date
          description: De start datum van dit product.
        eind_datum:
          type: string
          format: date
          description: De einddatum van dit product.
        bsn:
          type: string
          nullable: true
          description: De BSN van de product eigenaar, BSN van 8 karakters moet met
            een extra 0 beginnen.
        kvk:
          type: string
          nullable: true
          title: KVK nummer
          description: Het kvk nummer van de product eigenaar
          pattern: ^[0-9]*$
          maxLength: 8
          minLength: 8
      required:
      - aanmaak_datum
      - eind_datum
      - id
      - product_type
      - product_type_id
      - start_datum
      - update_datum
    ProductUpdate:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        gepubliceerd:
          type: boolean
          description: Geeft aan of het object getoond kan worden.
        aanmaak_datum:
          type: string
          format: date-time
          readOnly: true
          title: Created on
          description: De datum waarop het object is aangemaakt.
        update_datum:
          type: string
          format: date-time
          readOnly: true
          title: Updated on
          description: De datum waarop het object voor het laatst is gewijzigd.
        start_datum:
          type: string
          format: date
          description: De start datum van dit product.
        eind_datum:
          type: string
          format: date
          description: De einddatum van dit product.
        bsn:
          type: string
          nullable: true
          description: De BSN van de product eigenaar, BSN van 8 karakters moet met
            een extra 0 beginnen.
        kvk:
          type: string
          nullable: true
          title: KVK nummer
          description: Het kvk nummer van de product eigenaar
          pattern: ^[0-9]*$
          maxLength: 8
          minLength: 8
      required:
      - aanmaak_datum
      - eind_datum
      - id
      - start_datum
      - update_datum
    SimpleProductType:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        uniforme_product_naam:
          type: string
          format: uri
          description: Uri naar de UPN definitie.
        gepubliceerd:
          type: boolean
          description: Geeft aan of het object getoond kan worden.
        aanmaak_datum:
          type: string
          format: date-time
          readOnly: true
          title: Created on
          description: De datum waarop het object is aangemaakt.
        update_datum:
          type: string
          format: date-time
          readOnly: true
          title: Updated on
          description: De datum waarop het object voor het laatst is gewijzigd.
        naam:
          type: string
          description: naam van het product type.
          maxLength: 100
        samenvatting:
          type: string
          description: Korte beschrijving van het product type, maximaal 300 karakters.
          maxLength: 300
        beschrijving:
          type: string
          description: Product type beschrijving met WYSIWYG editor.
        keywords:
          type: array
          items:
            type: string
            maxLength: 100
          description: Lijst van keywords waarop kan worden gezocht.
      required:
      - aanmaak_datum
      - beschrijving
      - id
      - naam
      - uniforme_product_naam
      - update_datum
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
