name: ADR validation

on:
  push:
    branches:
      - master
      - stable/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:

  lint:
    name: Lint adr
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - producten
          - producttypen

    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: maykinmedia/open-api-workflows/actions/oas-lint@refactor/reusable-actions
        with:
          schema-path: src/${{ matrix.component }}-openapi.yaml
          node-version-file: '.nvmrc'
          spectral-version: '^6.15.0'
          ruleset: https://static.developer.overheid.nl/adr/2.1/ruleset.yaml

  validate:
    name: Validate adr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start docker containers
        run: docker compose up -d --build || ( docker compose logs >&2 && exit 1; )
      - name: Wait until uWSGI is running
        run: |
          until docker compose logs web | grep -q "spawned uWSGI worker"; do
            echo "uWSGI not running yet, waiting..."
            sleep 3
          done
      - name: Run ADR validation
        uses: addnab/docker-run-action@v3
        with:
          image: registry.gitlab.com/commonground/don/adr-validator:0.5.0
          options: --network host
          run: |
            adr-validator validate --details --fail-not-passed core "http://localhost:8000/producten/api/v1"
            adr-validator validate --details --fail-not-passed core "http://localhost:8000/producttypen/api/v1"

