name: generate-sdks

on:
  push:
    paths:
      - "src/openproduct/*-openapi.yaml"
      - ".github/workflows/generate-sdks.yml"
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-generate-sdks:
    uses: maykinmedia/open-api-workflows/.github/workflows/generate-sdks.yml@v5
    strategy:
      matrix:
        component:
          - producten
          - producttypen
    with:
      schema-path: 'src/openproduct/${{ matrix.component }}-openapi.yaml'
