name: lint-oas

on:
  push:
    paths:
      - "src/openproduct/*-openapi.yaml"
      - .github/workflows/lint-oas.yml
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-lint-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/lint-oas.yml@v5
    strategy:
      matrix:
        component:
          - producten
          - producttypen
    with:
      schema-path: 'src/openproduct/${{ matrix.component }}-openapi.yaml'
