name: check-oas

on:
  push:
  workflow_dispatch:

jobs:
  open-api-workflow-check-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/oas-check.yml@v5
    strategy:
      matrix:
        component:
          - producten
          - producttypen
    with:
      schema-path: 'src/${{ matrix.component }}-openapi.yaml'
      schema-command: 'bin/generate_api_schema.sh'
      python-version: '3.11'
      django-settings-module: 'openproduct.conf.ci'
